jar:
  fileUrl: C:/Users/Administrator/Pictures/webstatic

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.201.64.102/reading?serverTimezone=UTC&characterEncoding=utf-8
    #    url: jdbc:mysql://localhost/jancoblog?serverTimezone=UTC&characterEncoding=utf-8
    username: reading
    password: Cfw37MZS5hxETJGB
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  mvc:
    view:
      prefix: /
      suffix: .html
  web:
    resources:
      static-locations: file:${jar.fileUrl},classpath:/static/,
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  max-http-header-size: 1MB
  port: 8001
logging:
  level:
    com.jancoyan.jancoblog.mapper: debug

